//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipezeNyumbaWebApplication.TipezeNyumbaClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetails", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class UserDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateTimeCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userRoleForUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userSubscriptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime dateTimeCreated {
            get {
                return this.dateTimeCreatedField;
            }
            set {
                if ((this.dateTimeCreatedField.Equals(value) != true)) {
                    this.dateTimeCreatedField = value;
                    this.RaisePropertyChanged("dateTimeCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string userRoleForUser {
            get {
                return this.userRoleForUserField;
            }
            set {
                if ((object.ReferenceEquals(this.userRoleForUserField, value) != true)) {
                    this.userRoleForUserField = value;
                    this.RaisePropertyChanged("userRoleForUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string userSubscriptionType {
            get {
                return this.userSubscriptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.userSubscriptionTypeField, value) != true)) {
                    this.userSubscriptionTypeField = value;
                    this.RaisePropertyChanged("userSubscriptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string accountState {
            get {
                return this.accountStateField;
            }
            set {
                if ((object.ReferenceEquals(this.accountStateField, value) != true)) {
                    this.accountStateField = value;
                    this.RaisePropertyChanged("accountState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetailsToAddOrUpdate", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class UserDetailsToAddOrUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userRoleForUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userSubscriptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string userRoleForUser {
            get {
                return this.userRoleForUserField;
            }
            set {
                if ((object.ReferenceEquals(this.userRoleForUserField, value) != true)) {
                    this.userRoleForUserField = value;
                    this.RaisePropertyChanged("userRoleForUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string userSubscriptionType {
            get {
                return this.userSubscriptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.userSubscriptionTypeField, value) != true)) {
                    this.userSubscriptionTypeField = value;
                    this.RaisePropertyChanged("userSubscriptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccounState", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class UserAccounState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int accountStateIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountState {
            get {
                return this.accountStateField;
            }
            set {
                if ((object.ReferenceEquals(this.accountStateField, value) != true)) {
                    this.accountStateField = value;
                    this.RaisePropertyChanged("accountState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int accountStateID {
            get {
                return this.accountStateIDField;
            }
            set {
                if ((this.accountStateIDField.Equals(value) != true)) {
                    this.accountStateIDField = value;
                    this.RaisePropertyChanged("accountStateID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class UserType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userRoleForUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userRoleForUser {
            get {
                return this.userRoleForUserField;
            }
            set {
                if ((object.ReferenceEquals(this.userRoleForUserField, value) != true)) {
                    this.userRoleForUserField = value;
                    this.RaisePropertyChanged("userRoleForUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userTypeID {
            get {
                return this.userTypeIDField;
            }
            set {
                if ((this.userTypeIDField.Equals(value) != true)) {
                    this.userTypeIDField = value;
                    this.RaisePropertyChanged("userTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSubscriptionType", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class UserSubscriptionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subscriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subscriptionTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subscription {
            get {
                return this.subscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.subscriptionField, value) != true)) {
                    this.subscriptionField = value;
                    this.RaisePropertyChanged("subscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subscriptionTypeID {
            get {
                return this.subscriptionTypeIDField;
            }
            set {
                if ((this.subscriptionTypeIDField.Equals(value) != true)) {
                    this.subscriptionTypeIDField = value;
                    this.RaisePropertyChanged("subscriptionTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HouseDetails", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class HouseDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bedroomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateHouseWillBeAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateUploadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fenceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int houseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string houseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool masterBedroomEnsuiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeOfPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numberOfGaragesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumber2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool selfContainedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string whatsAppContactNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bedrooms {
            get {
                return this.bedroomsField;
            }
            set {
                if ((this.bedroomsField.Equals(value) != true)) {
                    this.bedroomsField = value;
                    this.RaisePropertyChanged("bedrooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateHouseWillBeAvailable {
            get {
                return this.dateHouseWillBeAvailableField;
            }
            set {
                if ((this.dateHouseWillBeAvailableField.Equals(value) != true)) {
                    this.dateHouseWillBeAvailableField = value;
                    this.RaisePropertyChanged("dateHouseWillBeAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateUploaded {
            get {
                return this.dateUploadedField;
            }
            set {
                if ((this.dateUploadedField.Equals(value) != true)) {
                    this.dateUploadedField = value;
                    this.RaisePropertyChanged("dateUploaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fenceType {
            get {
                return this.fenceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.fenceTypeField, value) != true)) {
                    this.fenceTypeField = value;
                    this.RaisePropertyChanged("fenceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int houseID {
            get {
                return this.houseIDField;
            }
            set {
                if ((this.houseIDField.Equals(value) != true)) {
                    this.houseIDField = value;
                    this.RaisePropertyChanged("houseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string houseState {
            get {
                return this.houseStateField;
            }
            set {
                if ((object.ReferenceEquals(this.houseStateField, value) != true)) {
                    this.houseStateField = value;
                    this.RaisePropertyChanged("houseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool masterBedroomEnsuite {
            get {
                return this.masterBedroomEnsuiteField;
            }
            set {
                if ((this.masterBedroomEnsuiteField.Equals(value) != true)) {
                    this.masterBedroomEnsuiteField = value;
                    this.RaisePropertyChanged("masterBedroomEnsuite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modeOfPayment {
            get {
                return this.modeOfPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.modeOfPaymentField, value) != true)) {
                    this.modeOfPaymentField = value;
                    this.RaisePropertyChanged("modeOfPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numberOfGarages {
            get {
                return this.numberOfGaragesField;
            }
            set {
                if ((this.numberOfGaragesField.Equals(value) != true)) {
                    this.numberOfGaragesField = value;
                    this.RaisePropertyChanged("numberOfGarages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber1 {
            get {
                return this.phoneNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumber1Field, value) != true)) {
                    this.phoneNumber1Field = value;
                    this.RaisePropertyChanged("phoneNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber2 {
            get {
                return this.phoneNumber2Field;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumber2Field, value) != true)) {
                    this.phoneNumber2Field = value;
                    this.RaisePropertyChanged("phoneNumber2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool selfContained {
            get {
                return this.selfContainedField;
            }
            set {
                if ((this.selfContainedField.Equals(value) != true)) {
                    this.selfContainedField = value;
                    this.RaisePropertyChanged("selfContained");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string whatsAppContactNumber {
            get {
                return this.whatsAppContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.whatsAppContactNumberField, value) != true)) {
                    this.whatsAppContactNumberField = value;
                    this.RaisePropertyChanged("whatsAppContactNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HousePaymentMode", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class HousePaymentMode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int modeOfPaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int modeOfPaymentID {
            get {
                return this.modeOfPaymentIDField;
            }
            set {
                if ((this.modeOfPaymentIDField.Equals(value) != true)) {
                    this.modeOfPaymentIDField = value;
                    this.RaisePropertyChanged("modeOfPaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentMode {
            get {
                return this.paymentModeField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentModeField, value) != true)) {
                    this.paymentModeField = value;
                    this.RaisePropertyChanged("paymentMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HouseFenceType", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class HouseFenceType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseFensetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fenceTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseFensetype {
            get {
                return this.HouseFensetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseFensetypeField, value) != true)) {
                    this.HouseFensetypeField = value;
                    this.RaisePropertyChanged("HouseFensetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fenceTypeID {
            get {
                return this.fenceTypeIDField;
            }
            set {
                if ((this.fenceTypeIDField.Equals(value) != true)) {
                    this.fenceTypeIDField = value;
                    this.RaisePropertyChanged("fenceTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HouseForRentState", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class HouseForRentState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int houseStateIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseStatus {
            get {
                return this.HouseStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseStatusField, value) != true)) {
                    this.HouseStatusField = value;
                    this.RaisePropertyChanged("HouseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int houseStateID {
            get {
                return this.houseStateIDField;
            }
            set {
                if ((this.houseStateIDField.Equals(value) != true)) {
                    this.houseStateIDField = value;
                    this.RaisePropertyChanged("houseStateID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistrictInMalawi", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class DistrictInMalawi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int districtIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int districtID {
            get {
                return this.districtIDField;
            }
            set {
                if ((this.districtIDField.Equals(value) != true)) {
                    this.districtIDField = value;
                    this.RaisePropertyChanged("districtID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipezeNyumbaClientService.ITipezeNyumbaService")]
    public interface ITipezeNyumbaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUsers", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUsersResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUsers", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUsersResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/AddANewUser", ReplyAction="http://tempuri.org/ITipezeNyumbaService/AddANewUserResponse")]
        bool AddANewUser(TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetailsToAddOrUpdate newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/AddANewUser", ReplyAction="http://tempuri.org/ITipezeNyumbaService/AddANewUserResponse")]
        System.Threading.Tasks.Task<bool> AddANewUserAsync(TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetailsToAddOrUpdate newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserProfile", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserProfileResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails GetUserProfile(int userID, string userToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserProfile", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserProfileResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails> GetUserProfileAsync(int userID, string userToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationToken", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationTokenResponse")]
        string GetAuntheticationToken(string phoneNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationToken", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationTokenResponse")]
        System.Threading.Tasks.Task<string> GetAuntheticationTokenAsync(string phoneNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserAccountStates", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserAccountStatesResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserAccounState[] GetUserAccountStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserAccountStates", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserAccountStatesResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserAccounState[]> GetUserAccountStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserRoles", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserRolesResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserType[] GetUserRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserRoles", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserRolesResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserType[]> GetUserRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserSubscriptionTypes", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserSubscriptionTypesResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserSubscriptionType[] GetUserSubscriptionTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserSubscriptionTypes", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserSubscriptionTypesResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserSubscriptionType[]> GetUserSubscriptionTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetSpecificHouse", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetSpecificHouseResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails GetSpecificHouse(int houseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetSpecificHouse", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetSpecificHouseResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails> GetSpecificHouseAsync(int houseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrict", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrictResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[] GetAllHousesByDistrict(string district);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrict", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrictResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[]> GetAllHousesByDistrictAsync(string district);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailable", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailableResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[] GetAllHousesByDateHouseAvailable(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailable", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailableResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[]> GetAllHousesByDateHouseAvailableAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRange", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRangeResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[] GetAllHousesByDateRange(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRange", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRangeResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[]> GetAllHousesByDateRangeAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetHousePaymentModes", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetHousePaymentModesResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.HousePaymentMode[] GetHousePaymentModes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetHousePaymentModes", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetHousePaymentModesResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HousePaymentMode[]> GetHousePaymentModesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetHouseFenceType", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetHouseFenceTypeResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseFenceType[] GetHouseFenceType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetHouseFenceType", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetHouseFenceTypeResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseFenceType[]> GetHouseFenceTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetHouseForRentStates", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetHouseForRentStatesResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseForRentState[] GetHouseForRentStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetHouseForRentStates", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetHouseForRentStatesResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseForRentState[]> GetHouseForRentStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetDistrictsInMalawi", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetDistrictsInMalawiResponse")]
        TipezeNyumbaWebApplication.TipezeNyumbaClientService.DistrictInMalawi[] GetDistrictsInMalawi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetDistrictsInMalawi", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetDistrictsInMalawiResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.DistrictInMalawi[]> GetDistrictsInMalawiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/AddAHouse", ReplyAction="http://tempuri.org/ITipezeNyumbaService/AddAHouseResponse")]
        string AddAHouse(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails newHouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/AddAHouse", ReplyAction="http://tempuri.org/ITipezeNyumbaService/AddAHouseResponse")]
        System.Threading.Tasks.Task<string> AddAHouseAsync(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails newHouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/UpdateHouseDetails", ReplyAction="http://tempuri.org/ITipezeNyumbaService/UpdateHouseDetailsResponse")]
        string UpdateHouseDetails(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails houseDetailsFromClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/UpdateHouseDetails", ReplyAction="http://tempuri.org/ITipezeNyumbaService/UpdateHouseDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateHouseDetailsAsync(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails houseDetailsFromClient);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITipezeNyumbaServiceChannel : TipezeNyumbaWebApplication.TipezeNyumbaClientService.ITipezeNyumbaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipezeNyumbaServiceClient : System.ServiceModel.ClientBase<TipezeNyumbaWebApplication.TipezeNyumbaClientService.ITipezeNyumbaService>, TipezeNyumbaWebApplication.TipezeNyumbaClientService.ITipezeNyumbaService {
        
        public TipezeNyumbaServiceClient() {
        }
        
        public TipezeNyumbaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipezeNyumbaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipezeNyumbaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipezeNyumbaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public bool AddANewUser(TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetailsToAddOrUpdate newUser) {
            return base.Channel.AddANewUser(newUser);
        }
        
        public System.Threading.Tasks.Task<bool> AddANewUserAsync(TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetailsToAddOrUpdate newUser) {
            return base.Channel.AddANewUserAsync(newUser);
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails GetUserProfile(int userID, string userToken) {
            return base.Channel.GetUserProfile(userID, userToken);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserDetails> GetUserProfileAsync(int userID, string userToken) {
            return base.Channel.GetUserProfileAsync(userID, userToken);
        }
        
        public string GetAuntheticationToken(string phoneNumber, string password) {
            return base.Channel.GetAuntheticationToken(phoneNumber, password);
        }
        
        public System.Threading.Tasks.Task<string> GetAuntheticationTokenAsync(string phoneNumber, string password) {
            return base.Channel.GetAuntheticationTokenAsync(phoneNumber, password);
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserAccounState[] GetUserAccountStates() {
            return base.Channel.GetUserAccountStates();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserAccounState[]> GetUserAccountStatesAsync() {
            return base.Channel.GetUserAccountStatesAsync();
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserType[] GetUserRoles() {
            return base.Channel.GetUserRoles();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserType[]> GetUserRolesAsync() {
            return base.Channel.GetUserRolesAsync();
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserSubscriptionType[] GetUserSubscriptionTypes() {
            return base.Channel.GetUserSubscriptionTypes();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.UserSubscriptionType[]> GetUserSubscriptionTypesAsync() {
            return base.Channel.GetUserSubscriptionTypesAsync();
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails GetSpecificHouse(int houseID) {
            return base.Channel.GetSpecificHouse(houseID);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails> GetSpecificHouseAsync(int houseID) {
            return base.Channel.GetSpecificHouseAsync(houseID);
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[] GetAllHousesByDistrict(string district) {
            return base.Channel.GetAllHousesByDistrict(district);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[]> GetAllHousesByDistrictAsync(string district) {
            return base.Channel.GetAllHousesByDistrictAsync(district);
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[] GetAllHousesByDateHouseAvailable(System.DateTime date) {
            return base.Channel.GetAllHousesByDateHouseAvailable(date);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[]> GetAllHousesByDateHouseAvailableAsync(System.DateTime date) {
            return base.Channel.GetAllHousesByDateHouseAvailableAsync(date);
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[] GetAllHousesByDateRange(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetAllHousesByDateRange(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails[]> GetAllHousesByDateRangeAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetAllHousesByDateRangeAsync(startDate, endDate);
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.HousePaymentMode[] GetHousePaymentModes() {
            return base.Channel.GetHousePaymentModes();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HousePaymentMode[]> GetHousePaymentModesAsync() {
            return base.Channel.GetHousePaymentModesAsync();
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseFenceType[] GetHouseFenceType() {
            return base.Channel.GetHouseFenceType();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseFenceType[]> GetHouseFenceTypeAsync() {
            return base.Channel.GetHouseFenceTypeAsync();
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseForRentState[] GetHouseForRentStates() {
            return base.Channel.GetHouseForRentStates();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseForRentState[]> GetHouseForRentStatesAsync() {
            return base.Channel.GetHouseForRentStatesAsync();
        }
        
        public TipezeNyumbaWebApplication.TipezeNyumbaClientService.DistrictInMalawi[] GetDistrictsInMalawi() {
            return base.Channel.GetDistrictsInMalawi();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaWebApplication.TipezeNyumbaClientService.DistrictInMalawi[]> GetDistrictsInMalawiAsync() {
            return base.Channel.GetDistrictsInMalawiAsync();
        }
        
        public string AddAHouse(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails newHouse) {
            return base.Channel.AddAHouse(newHouse);
        }
        
        public System.Threading.Tasks.Task<string> AddAHouseAsync(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails newHouse) {
            return base.Channel.AddAHouseAsync(newHouse);
        }
        
        public string UpdateHouseDetails(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails houseDetailsFromClient) {
            return base.Channel.UpdateHouseDetails(houseDetailsFromClient);
        }
        
        public System.Threading.Tasks.Task<string> UpdateHouseDetailsAsync(TipezeNyumbaWebApplication.TipezeNyumbaClientService.HouseDetails houseDetailsFromClient) {
            return base.Channel.UpdateHouseDetailsAsync(houseDetailsFromClient);
        }
    }
}
